# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin/ui/table_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TablePage(object):
    def setupUi(self, TablePage):
        TablePage.setObjectName("TablePage")
        self.verticalLayout = QtWidgets.QVBoxLayout(TablePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBar = QtWidgets.QHBoxLayout()
        self.topBar.setObjectName("topBar")
        self.btnBack = QtWidgets.QPushButton(TablePage)
        self.btnBack.setObjectName("btnBack")
        self.topBar.addWidget(self.btnBack)
        self.inputSearch = QtWidgets.QLineEdit(TablePage)
        self.inputSearch.setObjectName("inputSearch")
        self.topBar.addWidget(self.inputSearch)
        self.btnFilter = QtWidgets.QPushButton(TablePage)
        self.btnFilter.setObjectName("btnFilter")
        self.topBar.addWidget(self.btnFilter)
        self.btnAdd = QtWidgets.QPushButton(TablePage)
        self.btnAdd.setObjectName("btnAdd")
        self.topBar.addWidget(self.btnAdd)
        self.verticalLayout.addLayout(self.topBar)
        self.tableWidget = QtWidgets.QTableWidget(TablePage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(TablePage)

    def retranslateUi(self, TablePage):
        _translate = QtCore.QCoreApplication.translate
        self.btnBack.setText(_translate("TablePage", "Назад"))
        self.inputSearch.setPlaceholderText(_translate("TablePage", "Поиск..."))
        self.btnFilter.setText(_translate("TablePage", "Фильтр"))
        self.btnAdd.setText(_translate("TablePage", "Добавить"))
